name: amplify_experiment
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^1.0.4
  flutter_riverpod: ^1.0.4
  flutter_hooks: ^0.18.5+1
  gap: ^2.0.0
  flex_color_scheme: ^5.1.0
  freezed_annotation: ^2.1.0
  amplify_flutter: ^0.6.5
  amplify_auth_cognito: ^0.6.5
  pinput: ^2.2.12
  amplify_datastore: ^0.6.5
  animations: ^2.0.3
  flextras: ^0.0.2
  sliver_tools: ^0.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1

flutter: 
  uses-material-design: true

scripts:
  watch_gen: fvm flutter pub run build_runner watch --delete-conflicting-outputs